### PR TITLE
Decrease minimum size for recording window

### PR DESCRIPTION
**Pull request by MarcAnt01**
With the current UI, I prefer to keep the recording window resized, with this pull request I have reduced a bit more the minimum size for the window. Here's a preview of how it looks like
image

### CODE REVIEW

**Comment by robmikh** [comment]
Sorry it's taken me so long to look at this. I'm definitely in favor of allowing a more compact configuration, but the spacing starts to feel a bit cramped for the left column. 

I can take a look at what that would take, but if you have any ideas I'd likely be open to them.

**Comment by MarcAnt01** [comment]
I have to redo the pull request, since I have somehow deleted the fork. I can redo the pr, trying not to make the left column too small.
Down below you can see how the space optimization results in a more pleasant final effect. Simple Screen Recorder vs Fluent Screen Recorder, my fork of your app.
image

**Comment by robmikh** [comment]
Hey, that looks pretty good! Your screenshot made me realize something. Just so you know, the quality combo box controls more than just the resolution. It also determines bitrate. Just thought I'd mention that, as I realize now that I made the UI unclear here. 

It may be worth it to split resolution from bitrate. It was originally combined due to my laziness... but I think I'll be changing it. 

Here are the values when I dumped the resolutions with their bitrates if you're interested:
```
HD1080p - 18000000
HD720p - 9000000
Uhd2160p - 36000000
Uhd4320p - 72000000
```

**Comment by robmikh** [comment]
I'll accept this for now and work on fixing the UI for some extra clarity and variable margins. Thanks!

**Comment by MarcAnt01** [comment]
@robmikh my screen uses a 3000x200

> Hey, that looks pretty good! Your screenshot made me realize something. Just so you know, the quality combo box controls more than just the resolution. It also determines bitrate. Just thought I'd mention that, as I realize now that I made the UI unclear here.
> 
> It may be worth it to split resolution from bitrate. It was originally combined due to my laziness... but I think I'll be changing it.
> 
> Here are the values when I dumped the resolutions with their bitrates if you're interested:
> 
> ```
> HD1080p - 18000000
> HD720p - 9000000
> Uhd2160p - 36000000
> Uhd4320p - 72000000
> ```

I have noticed that it changed according to the resolution. But what about usescreensize one?

**Comment by robmikh** [comment]
The option to use the source's size doesn't effect the bitrate, only the resolution. The bitrate still comes from the selection in the quality combo box. It's not intuitive, sorry about that. 🙂

**Comment by MarcAnt01** [comment]
Ah OK, I will add another combobox, thanks for letting me know

**Pull request merged**
